import { createContext, useContext, useState } from "react";

const translations = {
  en: {
    // Sidebar
    admin: "ADMIN",
    superAdmin: "Super Admin",
    principal: "MAIN",
    overview: "Overview",
    reports: "Reports",
    users: "Users",
    partners: "Partners",
    community: "COMMUNITY",
    localMissions: "Local Missions",
    collectionPoints: "Collection Points",
    economy: "ECONOMY",
    pointsSystem: "Points System",
    physicalItems: "Physical Items",
    donations: "Donations",
    crowdfunding: "Crowdfunding",
    config: "CONFIG",
    analytics: "Analytics",
    notifications: "Notifications",
    faq: "FAQ",
    settings: "Settings",
    logout: "Logout",
    contacts: "Contacts",
    shopifyProducts: "Shopify Products",
    "validation-donations": "Donation Proofs",
    allCollections: "All Collections",
    pending: "Pending",
    rejected: "Rejected",
    supportMessages: "Support Messages",
    // Common UI
    searchPlaceholder: "Search...",
    sortBy: "SORT BY:",
    dateLabel: "DATE",
    statusLabel: "STATUS",
    actionsLabel: "ACTIONS",
    previous: "Previous",
    next: "Next",
    showing: "Showing",
    to: "to",
    of: "of",
    results: "results",
    allCategories: "All categories",
    allTypes: "All types",
    allStatuses: "All statuses",
    dateDesc: "Date (Newest)",
    dateAsc: "Date (Oldest)",
    nameAsc: "Name (A-Z)",
    nameDesc: "Name (Z-A)",
    emailAsc: "Email (A-Z)",
    companyAsc: "Company (A-Z)",
    ptsDesc: "Points (Highest)",
    ptsAsc: "Points (Lowest)",
    noItemsFound: "No items found.",
    noRequestsFound: "No requests found.",
    noReportsFound: "No reports found.",
    noUsersFound: "No users found matching your criteria.",
    noPartnersFound: "No partners found.",
    noPartnersPending: "No pending partners.",
    noMissionsFound: "No missions found.",
    searchPartnerPlaceholder: "Search for a partner...",
    allSpecies: "All species",
    animalSpecies: "Species",
    cat: "Cat",
    dog: "Dog",
    bird: "Bird",
    rabbit: "Rabbit",
    otherSpecies: "Other",
    commentsLabel: "Comments",
    joinedDate: "Joined Date",
    companyName: "Company Name",
    allPartners: "All Partners",
    approvePartnerTitle: "Approve Partner",
    confirmApproveMessage: "Are you sure you want to approve this partner?",
    rejectPartnerTitle: "Reject Partner",
    confirmRejectMessage: "Are you sure you want to reject this partner?",
    cityLabel: "City",
    pointsRequired: "Points Required",
    itemImage: "Item Image",
    productType: "Product",
    giftCardType: "Gift Card",
    stockLabel: "Stock",
    titleLabel: "Title",
    descriptionLabel: "Description",
    categoryLabel: "Category",
    missionPhoto: "Mission Photo",
    editMissionTitle: "Edit Mission",
    createMissionTitle: "Create Mission",
    deleteMissionTitle: "Delete Mission",
    confirmDeleteMission: "Are you sure you want to delete this mission?",
    toComeLabel: "To Come",
    participants: "Participants",
    durationLabel: "Duration",
    paymentMethodLabel: "Payment Method",
    printBtn: "Print",
    emailReceipt: "Email Receipt",
    closeBtn: "Close",
    sendingLabel: "Sending...",
    veterinarian: "Veterinarian",
    authorityLabel: "Authority",
    countryLabel: "Country",
    nameLabel: "Name",
    websiteLabel: "Website",
    latitudeLabel: "Latitude",
    longitudeLabel: "Longitude",
    photoLabel: "Photo",
    deletePointTitle: "Delete Collection Point",
    confirmDeletePoint: "Are you sure you want to delete this collection point?",
    addPointLabel: "Add Collection Point",
    editPointLabel: "Edit Collection Point",
    generalInfo: "General Information",
    informationsLabel: "Information",
    localisationLabel: "Localization",
    janShort: "Jan",
    febShort: "Feb",
    marShort: "Mar",
    aprShort: "Apr",
    searchLocationPlaceholder: "Search location...",
    findBtn: "Find",
    clickToPin: "CLICK TO PIN",
    visualPreview: "Visual Preview",
    existingPhoto: "Existing Photo",
    uploadPhoto: "Upload photo",
    dragDrop: "Click or drag & drop",
    locationDetails: "Location Details",
    mapLocation: "Map Location",
    closeView: "Close View",
    discardBtn: "Discard",
    saveChanges: "Save Changes",
    createBtn: "Create",
    clearFilters: "Clear all filters",
    totalCount: "Total",
    selectOption: "Select...",
    titleAsc: "Title (A-Z)",
    titleDesc: "Title (Z-A)",
    allRoles: "All roles",
    userRole: "User",
    partnerRole: "Partner",
    adminRole: "Admin",
    blocked: "Blocked",
    updateStatusTitle: "Update Status",
    confirmUpdateMessage: "Are you sure you want to change the status?",
    confirmUpdateMessageTo: "Are you sure you want to change the status to",
    globalConfig: "Global Configuration",
    configUpdateMsg: "Changes to the scale will be applied immediately for all future user actions. Existing points will not be affected.",
    clickToSimulate: "Click to enable/disable a rule (simulation)",
    boosterTitle: "Boost donations this weekend?",
    boosterDesc: "Enable a x2 multiplier on all physical donation deposits to encourage the SPA.",
    activateNow: "ACTIVATE NOW",
    currentValuePerAction: "Current value per action",
    thisMonth: "This month",
    converted: "Converted",
    unused: "Unused",
    activePointsLabel: "active collection points",
    goal: "goal",
    of: "of",
    noDescription: "No description",
    noComments: "No comments yet.",
    noNotifHistory: "No notification history.",
    noAddress: "No address",
    noDataFound: "No data found.",
    updating: "Updating...",
    // Topbar Subtitles
    registeredCount: "registered",
    totalCount: "total",
    pendingCountLabel: "pending",
    inProgressCount: "in progress",
    collectionPointsCount: "collection points",
    ptsDistributedCount: "pts distributed",
    itemsInCatalog: "items in catalog",
    donationsCount: "donations",
    sentCount: "sent",
    // Statuses
    active: "Active",
    inactive: "Inactive",
    suspended: "Suspended",
    banned: "Banned",
    pending: "Pending",
    rejected: "Rejected",
    lost: "Lost",
    sighted: "Sighted",
    resolved: "Resolved",
    found: "Found",
    rescued: "Rescued",
    shipped: "Shipped",
    delivered: "Delivered",
    cancelled: "Cancelled",
    approved: "Approved",
    // Validation Donations
    physicalDonationLabel: "Physical Donation",
    unknownPoint: "Unknown point",
    ptsToAttribute: "Points to attribute",
    declaredQuantity: "Declared quantity:",
    toValidate: "to validate",
    vsLastMonth: "vs last month",
    loadingLabel: "Loading...",
    validateDonationTitle: "Validate Donation",
    rejectDonationTitle: "Reject Donation",
    optionalNote: "Note (Optional)",
    rejectionReason: "Reason for rejection",
    food: "Food",
    litter: "Litter",
    toys: "Toys & accessories",
    medicine: "Medicine / care",
    other: "Other",
    blurredPhoto: "Blurred or unreadable photo",
    itemNotVisible: "Item not visible on photo",
    pointNotRecognized: "Collection point not recognized",
    // Login
    loginTitle: "Log in",
    emailLabel: "Email",
    passwordLabel: "Password",
    rememberMe: "Keep me signed in",
    forgotPassword: "Forgotten password",
    signInBtn: "Sign In",
    signingIn: "Signing in...",
    adminOnly: "Admin access only",
    welcomeBack: "Welcome back",
    loginFailed: "Login failed. Check your credentials.",
    networkError: "Network error. Please try again.",
    enterEmail: "Enter my email",
    enterPassword: "Enter my password",
    fillAllFields: "Please fill in all fields.",
    accessDeniedAdmin: "Access denied. Admin accounts only.",
    // Topbar
    dashboardSub: "Dashboard — Hesteka Admin",
    newReport: "New Report",
    viewAll: "View All",
    markAllRead: "Mark all read",
    noNotifs: "No recent notifications",
    // Profile Modal
    firstName: "First Name",
    lastName: "Last Name",
    phone: "Phone",
    company: "Company",
    address: "Address",
    bioIntro: "Bio / Intro",
    bioPlaceholder: "Write something about yourself...",
    close: "Close",
    cancel: "Cancel",
    saveProfile: "Save Profile",
    saving: "Saving...",
    // Stats
    usersLabel: "USERS",
    activeReports: "ACTIVE REPORTS",
    resolved: "RESOLVED",
    donationsCollected: "DONATIONS COLLECTED",
    pointsDistributed: "POINTS DISTRIBUTED",
    partnersLabel: "PARTNERS",
    activeMissions: "ACTIVE MISSIONS",
    downloads: "DOWNLOADS",
    // Sub stats
    thisWeek: "this week",
    pending: "pending",
    rate: "Rate",
    thisMonth206: "this month",
    pendingPoints: "pending",
    inValidation: "in validation",
    inProgress: "in progress",
    thisMonth55: "this month",
    // Map
    mapTitle: "Reports Map",
    view: "View",
    activeReportsCount: "active reports",
    // Activity
    recentActivity: "Recent Activity",
    act1: "lost dog report, Salon-de-Provence",
    act1time: "2 min ago",
    act2: "just registered",
    act2time: "8 min ago",
    act3: "20€ donation received \u2013 Mission SPA Salon",
    act3time: "15 min ago",
    act4: "SPA Salon validated 4 participations for Dogs Walk mission",
    act4time: "22 min ago",
    act5: "report resolved \u2705",
    act5time: "1h ago",
    whiteKitten: "White Kitten",
    // Chart
    reportTypes: "Report Types",
    lost: "Lost",
    found: "Found",
    sheltered: "Sheltered",
    injured: "Injured",
    // Crowdfunding
    goal: "/ 5,000€ goal",
    donors: "Donors",
    remaining: "Remaining",
    left: "Left",
    daysRemainingValue: "18d",
    // Signalements Page
    reportsTitle: "Reports",
    reportsSub: "89 active - 342 resolved",
    totalActive: "TOTAL ACTIVE",
    resolvedLabel: "RESOLVED",
    pendingLabel: "PENDING",
    resolutionRate: "RESOLUTION RATE",
    allReports: "All Reports",
    animal: "ANIMAL",
    type: "TYPE",
    status: "STATUS",
    location: "LOCATION",
    user: "USER",
    date: "DATE",
    actions: "ACTIONS",
    viewBtn: "View",
    editBtn: "Edit",
    deleteBtn: "Delete",
    contactsTitle: "Contacts",
    contactsSub: "Useful contacts for the community",
    addContact: "Add Contact",
    contactName: "NAME",
    contactType: "TYPE",
    contactAddress: "ADDRESS",
    contactPhone: "PHONE",
    contactEmail: "EMAIL",
    allContacts: "All Contacts",
    shelter: "Shelter",
    vet: "Vet",
    association: "Association",
    partner: "Partner",
    editContact: "Edit Contact",
    viewContact: "View Contact",
    validateBtn: "Validate",
    spamBtn: "Spam",
    // Users Page
    usersTitle: "Users",
    usersSub: "1,284 registered",
    totalRegistered: "TOTAL REGISTERED",
    activeLabel: "ACTIVE",
    suspendedLabel: "SUSPENDED",
    newThisMonth: "NEW THIS MONTH",
    allUsers: "All Users",
    email: "EMAIL",
    points: "POINTS",
    missions: "MISSIONS",
    registration: "REGISTRATION",
    detailsBtn: "Details",
    suspendBtn: "Suspend",
    reactivateBtn: "Reactivate",
    banBtn: "Ban",
    exportBtn: "Export",
    // Partners Page
    partnersTitle: "Partners",
    partnersSub: "14 active - 3 pending",
    pendingValidation: "Pending Validation",
    activePartners: "Active Partners",
    pendingMissionValidations: "Pending Mission Validations",
    participants: "PARTICIPANTS",
    validateAll: "Validate All",
    addPartner: "Add Partner",
    // Missions Page
    missionsTitle: "Local Missions",
    missionsSub: "8 missions - 2 in progress",
    inProgressLabel: "IN PROGRESS",
    toComeLabel: "TO COME",
    finishedLabel: "FINISHED",
    pointsAttributed: "POINTS ATTRIBUTED",
    allMissions: "All Missions",
    createMission: "Create Mission",
    addMission: "Add Mission",
    cancelBtn: "Cancel",
    // Points de collecte Page
    collectionPointsTitle: "Collection Points",
    collectionPointsSub: "22 active points",
    pointsList: "List of collection points",
    addPoint: "Add point",
    deactivateBtn: "Deactivate",
    // Points Page
    pointsTitle: "Points System",
    pointsSub: "18,450 pts distributed",
    distributedLabel: "DISTRIBUTED",
    exchangedLabel: "EXCHANGED",
    expiredLabel: "EXPIRED",
    pointsScale: "Points Scale",
    usageRules: "Usage Rules",
    transactionHistory: "Transaction History",
    saveScale: "Save Scale",
    saveBtn: "Save",
    validityDuration: "Validity duration - 12 months",
    monthlyCeiling: "Monthly ceiling - 500 pts",
    doublePoints: "Double points active",
    pointsOnDonations: "Points on donations",
    // Physical Items Page
    itemsTitle: "Physical Items",
    itemsSub: "Exchangeable catalog",
    addItem: "Add an item",
    exchangeRequests: "Exchange Requests",
    article: "ARTICLE",
    address: "ADDRESS",
    shippedBtn: "Shipped",
    restockBtn: "Restock",
    outOfStock: "Out of Stock",
    // Donations Page
    donationsTitle: "Donations",
    donationsSub: "4,820€ collected",
    totalCollected: "TOTAL COLLECTED",
    returnedAssos: "RETURNED TO ASSOS",
    averageBasket: "AVERAGE BASKET",
    allTransactions: "All Transactions",
    donator: "DONATOR",
    amount: "AMOUNT",
    association: "ASSOCIATION",
    fiscalReceipt: "Fiscal receipt",
    returnBtn: "Return",
    receiptBtn: "Receipt",
    // Crowdfunding Page
    crowdTitle: "Crowdfunding",
    crowdSub: "Ulule campaign - 83% reached",
    viewOnUlule: "View on Ulule",
    donorsList: "Donors List",
    counterpart: "COUNTERPART",
    confirmed: "Confirmed",
    collected: "collected",
    futureLaunch: "Future launch",
    // Analytics Page
    analyticsTitle: "Analytics",
    analyticsSub: "Global performance",
    sessionsMonth: "SESSIONS/MONTH",
    retention: "RETENTION",
    avgDuration: "AVG DURATION",
    conversion: "CONVERSION",
    reportsMonth: "Reports per month",
    activeZones: "Most active zones",
    zone1: "Provence-Alpes-Cote d'Azur",
    zone2: "Ile-de-France",
    zone3: "Occitanie",
    zone4: "Auvergne-Rhone-Alpes",
    // Notifications Page
    notifTitle: "Notifications",
    notifSub: "Community alerts",
    createAlert: "Create an alert",
    geoTarget: "GEOGRAPHIC TARGETING",
    userType: "USER TYPE",
    message: "MESSAGE",
    sendAlert: "Send alert",
    allFrance: "All France",
    pacaRegion: "PACA Region (South France)",
    opening: "Open",
    clicks: "Clicks",
    enterAlertMessage: "Enter your alert message...",
    notifHistory: "Notification history",
    // Settings Page
    settingsTitle: "Settings",
    settingsSub: "Platform configuration",
    adminTeam: "Admin Team",
    application: "Application",
    recentLogins: "Recent Logins",
    inviteAdmin: "Invite an admin",
    autoAlerts: "Automatic alerts",
    pushNotifs: "Push notifs enabled",
    maintenanceMode: "Maintenance mode",
    disableAccess: "Disables user access",
    alertRadius: "Alert radius",
    defaultGeo: "Default geolocation",
    saveChanges: "Save changes",
    supportSettings: "Support Settings",
    supportEmailLabel: "Support Email",
    supportEmailSub: "Email displayed in the mobile app for user contact.",
    platformNameLabel: "Platform Name",
    platformNameSub: "General name used across the application.",
    faqManagement: "FAQ Management",
    addFaq: "Add FAQ",
    allCategories: "All Categories",
    questionLabel: "Question",
    answerLabel: "Answer",
    noFaqsFound: "No FAQs found matching your criteria.",
    faqTitle: "FAQ",
    faqSub: "Manage your platform's help center content.",
    superAdminBadge: "SUPER ADMIN",
    editFaqGroup: "Edit FAQ Group",
    addFaqGroup: "Add FAQ Group",
    viewFaqGroup: "View FAQ Group",
    viewFaq: "View FAQ",
    groupOrder: "Group Order",
    qaOrder: "Q&A Order",
    questionsAndAnswers: "Questions & Answers",
    addQa: " Add Q&A",
    englishLang: "English",
    frenchLang: "Français",
    englishQuestionPlaceholder: "English question...",
    englishAnswerPlaceholder: "English answer...",
    frenchQuestionPlaceholder: "French question...",
    frenchAnswerPlaceholder: "French answer...",
    atLeastOneQa: "Please add at least one Q&A.",
    deleteFaqGroupMessage: "Are you sure you want to delete this FAQ group? This action cannot be undone.",
    questionsCount: "QUESTIONS",
    questionsText: "Questions",
    // Validation Dons Page
    valDonationsTitle: "Donation Proofs",
    valDonationsSub: "4 donations pending validation",
    pendingValidationDon: "PENDING",
    validatedThisMonth: "VALIDATED THIS MONTH",
    refused: "REFUSED",
    ptsGranted: "PTS GRANTED",
    howItWorks: "How it works?",
    howItWorksDesc: "The user takes a photo of their deposit in a partner collection point and submits it via the app. You validate or refuse here. Points (+15 pts) are automatically attributed after validation.",
    donsPendingVal: "Donations pending validation",
    recentValidations: "Recent validations",
    depositsThisMonth: "Deposits this month",
    refusalReasons: "Frequent refusal reasons",
    validatePts: "Validate +15 pts",
    refuseBtn: "Refuse",
    enlargePhoto: "Enlarge photo",
    // Report Form Additions
    createReport: "Create Report",
    editReportTitle: "Edit Report",
    createReportTitle: "Create New Report",
    newRecord: "New Record",
    fieldRequired: "This field is required",
    failedSaveReport: "Failed to save report",
    animalName: "Animal Name",
    breed: "Breed",
    gender: "Gender",
    male: "Male",
    female: "Female",
    age: "Age",
    junior: "Junior",
    adult: "Adult",
    senior: "Senior",
    eventDate: "Event Date",
    locationAddress: "Location Address",
    hasMicrochip: "Has Microchip",
    hasTattoo: "Has Tattoo",
    hasCollarOrHarness: "Has Collar/Harness",
    yes: "Yes",
    no: "No",
    unknown: "Unknown",
    animalPhoto: "Animal Photo",
  },
  fr: {
    admin: "ADMIN",
    superAdmin: "Super Admin",
    principal: "PRINCIPAL",
    overview: "Vue globale",
    reports: "Signalements",
    users: "Utilisateurs",
    partners: "Partenaires",
    community: "COMMUNAUT\u00C9",
    localMissions: "Missions locales",
    collectionPoints: "Points de collecte",
    economy: "\u00C9CONOMIE",
    pointsSystem: "Syst\u00E8me de points",
    physicalItems: "Articles physiques",
    donations: "Dons",
    crowdfunding: "Financement participatif",
    config: "CONFIG",
    analytics: "Statistiques",
    notifications: "Alertes",
    faq: "FAQ",
    settings: "Param\u00E8tres",
    logout: "D\u00E9connexion",
    contacts: "R\u00E9pertoire",
    shopifyProducts: "Produits Shopify",
    "validation-donations": "Preuves de Don",
    allCollections: "Toutes les collections",
    pending: "En attente",
    rejected: "Rejeté",
    supportMessages: "Messages de support",
    // Common UI
    searchPlaceholder: "Rechercher...",
    sortBy: "TRIER PAR:",
    dateLabel: "DATE",
    statusLabel: "STATUT",
    actionsLabel: "ACTIONS",
    previous: "Pr\u00E9c\u00E9dent",
    next: "Suivant",
    showing: "Affichage de",
    to: "\u00E0",
    of: "sur",
    results: "r\u00E9sultats",
    allCategories: "Toutes les cat\u00E9gories",
    allTypes: "Tous les types",
    allStatuses: "Tous les statuts",
    dateDesc: "Date (Plus r\u00E9cent)",
    dateAsc: "Date (Plus ancien)",
    nameAsc: "Nom (A-Z)",
    nameDesc: "Nom (Z-A)",
    emailAsc: "Email (A-Z)",
    companyAsc: "Entreprise (A-Z)",
    ptsDesc: "Points (Plus \u00E9lev\u00E9)",
    ptsAsc: "Points (Plus bas)",
    noItemsFound: "Aucun article trouv\u00E9.",
    noRequestsFound: "Aucune demande trouv\u00E9e.",
    noReportsFound: "Aucun signalement trouv\u00E9.",
    noUsersFound: "Aucun utilisateur trouv\u00E9 correspondant \u00E0 vos crit\u00E8res.",
    noPartnersFound: "Aucun partenaire trouv\u00E9.",
    noPartnersPending: "Aucun partenaire en attente.",
    noMissionsFound: "Aucune mission trouv\u00E9e.",
    searchPartnerPlaceholder: "Rechercher un partenaire...",
    allSpecies: "Toutes les esp\u00E8ces",
    animalSpecies: "Esp\u00E8ces",
    cat: "Chat",
    dog: "Chien",
    bird: "Oiseau",
    rabbit: "Lapin",
    otherSpecies: "Autre",
    commentsLabel: "Commentaires",
    joinedDate: "Date d'inscription",
    companyName: "Nom de l'entreprise",
    allPartners: "Tous les partenaires",
    approvePartnerTitle: "Approuver le partenaire",
    confirmApproveMessage: "Voulez-vous vraiment approuver ce partenaire ?",
    rejectPartnerTitle: "Rejeter le partenaire",
    confirmRejectMessage: "Voulez-vous vraiment rejeter ce partenaire ?",
    cityLabel: "Ville",
    pointsRequired: "Points requis",
    itemImage: "Image de l'article",
    productType: "Produit",
    giftCardType: "Bon d'achat",
    stockLabel: "Stock",
    titleLabel: "Titre",
    descriptionLabel: "Description",
    categoryLabel: "Catégorie",
    missionPhoto: "Photo de la mission",
    editMissionTitle: "Modifier la mission",
    createMissionTitle: "Créer une mission",
    deleteMissionTitle: "Supprimer la mission",
    confirmDeleteMission: "Voulez-vous vraiment supprimer cette mission ?",
    toComeLabel: "À venir",
    participants: "Participants",
    durationLabel: "Durée",
    paymentMethodLabel: "Méthode de paiement",
    printBtn: "Imprimer",
    emailReceipt: "Envoyer par e-mail",
    closeBtn: "Fermer",
    sendingLabel: "Envoi en cours...",
    veterinarian: "Vétérinaire",
    authorityLabel: "Autorité",
    countryLabel: "Pays",
    nameLabel: "Nom",
    websiteLabel: "Site web",
    latitudeLabel: "Latitude",
    longitudeLabel: "Longitude",
    photoLabel: "Photo",
    deletePointTitle: "Supprimer le point de collecte",
    confirmDeletePoint: "Voulez-vous vraiment supprimer ce point de collecte ?",
    addPointLabel: "Ajouter un point de collecte",
    editPointLabel: "Modifier le point de collecte",
    generalInfo: "Informations Générales",
    informationsLabel: "Informations",
    localisationLabel: "Localisation",
    janShort: "Jan",
    febShort: "F\u00E9v",
    marShort: "Mar",
    aprShort: "Avr",
    searchLocationPlaceholder: "Rechercher un lieu...",
    findBtn: "Trouver",
    clickToPin: "CLIQUER POUR \u00C9PINGLER",
    visualPreview: "Aper\u00E7u Visuel",
    existingPhoto: "Photo existante",
    uploadPhoto: "Charger une photo",
    dragDrop: "Cliquer ou glisser-d\u00E9poser",
    locationDetails: "D\u00E9tails de localisation",
    mapLocation: "Localisation sur la carte",
    closeView: "Fermer la vue",
    discardBtn: "Annuler",
    saveChanges: "Enregistrer les modifications",
    createBtn: "Cr\u00E9er",
    clearFilters: "Effacer les filtres",
    totalCount: "Total",
    selectOption: "S\u00E9lectionner...",
    titleAsc: "Titre (A-Z)",
    titleDesc: "Titre (Z-A)",
    allRoles: "Tous les rôles",
    userRole: "Utilisateur",
    partnerRole: "Partenaire",
    adminRole: "Admin",
    blocked: "Bloqué",
    updateStatusTitle: "Modifier le statut",
    confirmUpdateMessage: "Voulez-vous vraiment changer le statut ?",
    confirmUpdateMessageTo: "Voulez-vous vraiment changer le statut en",
    globalConfig: "Configuration Globale",
    configUpdateMsg: "Les modifications apport\u00E9es au bar\u00E8me seront appliqu\u00E9es imm\u00E9diatement pour toutes les futures actions des utilisateurs. Les points d\u00E9j\u00E0 acquis ne seront pas impact\u00E9s.",
    clickToSimulate: "Cliquez pour activer/d\u00E9sactiver une r\u00E8gle (simulation)",
    boosterTitle: "Booster les dons ce weekend ?",
    boosterDesc: "Activez un multiplicateur x2 sur tous les d\u00E9p\u00F4ts de dons physiques pour encourager la SPA.",
    activateNow: "ACTIVER MAINTENANT",
    currentValuePerAction: "Valeur actuelle par action",
    thisMonth: "Ce mois",
    converted: "Convertis",
    unused: "Non utilis\u00E9s",
    activePointsLabel: "points de collecte actifs",
    goal: "objectif",
    of: "sur",
    noDescription: "Aucune description",
    noComments: "Aucun commentaire pour le moment.",
    noNotifHistory: "Aucun historique de notification.",
    noAddress: "Aucune adresse",
    noDataFound: "Aucune donn\u00E9e trouv\u00E9e.",
    updating: "Mise \u00E0 jour...",
    // Topbar Subtitles
    registeredCount: "inscrits",
    totalCount: "total",
    pendingCountLabel: "en attente",
    inProgressCount: "en cours",
    collectionPointsCount: "points de collecte",
    ptsDistributedCount: "pts distribu\u00E9s",
    itemsInCatalog: "articles au catalogue",
    donationsCount: "dons",
    sentCount: "envoy\u00E9es",
    // Statuses
    active: "Actif",
    inactive: "Inactif",
    suspended: "Suspendu",
    banned: "Banni",
    pending: "En attente",
    rejected: "Rejet\u00E9",
    lost: "Perdu",
    sighted: "Signal\u00E9",
    resolved: "R\u00E9solu",
    found: "Trouv\u00E9",
    rescued: "Sauv\u00E9",
    shipped: "Exp\u00E9di\u00E9",
    delivered: "Livr\u00E9",
    cancelled: "Annul\u00E9",
    approved: "Approuv\u00E9",
    // Validation Donations
    physicalDonationLabel: "Donation physique",
    unknownPoint: "Point inconnu",
    ptsToAttribute: "Points \u00E0 attribuer",
    declaredQuantity: "Quantit\u00E9 d\u00E9clar\u00E9e :",
    toValidate: "\u00E0 valider",
    vsLastMonth: "vs mois d\u00E9rn.",
    loadingLabel: "Chargement...",
    validateDonationTitle: "Valider la donation",
    rejectDonationTitle: "Refuser la donation",
    optionalNote: "Note (Optionnel)",
    rejectionReason: "Raison du refus",
    food: "Croquettes / nourriture",
    litter: "Liti\u00E8re",
    toys: "Jouets & accessoires",
    medicine: "M\u00E9dicaments / soins",
    other: "Autre",
    blurredPhoto: "Photo floue ou illisible",
    itemNotVisible: "D\u00E9p\u00F4t non visible sur la photo",
    pointNotRecognized: "Point de collecte non reconnu",
    // Login
    loginTitle: "Connexion",
    emailLabel: "E-mail",
    passwordLabel: "Mot de passe",
    rememberMe: "Rester connect\u00E9",
    forgotPassword: "Mot de passe oubli\u00E9",
    signInBtn: "Se connecter",
    signingIn: "Connexion en cours...",
    adminOnly: "Acc\u00E8s administrateur uniquement",
    welcomeBack: "Bon retour",
    loginFailed: "Échec de la connexion. Vérifiez vos identifiants.",
    networkError: "Erreur réseau. Veuillez réessayer.",
    enterEmail: "Entrez mon e-mail",
    enterPassword: "Entrez mon mot de passe",
    fillAllFields: "Veuillez remplir tous les champs.",
    accessDeniedAdmin: "Acc\u00E8s refus\u00E9. Comptes administrateurs uniquement.",
    dashboardSub: "Tableau de bord \u2014 Hesteka Admin",
    newReport: "Nouveau signalement",
    viewAll: "Voir tout",
    markAllRead: "Tout marquer lu",
    noNotifs: "Aucune notification r\u00E9cente",
    firstName: "Pr\u00E9nom",
    lastName: "Nom",
    phone: "T\u00E9l\u00E9phone",
    company: "Entreprise",
    address: "Adresse",
    bioIntro: "Bio / Pr\u00E9sentation",
    bioPlaceholder: "\u00C9crivez quelque chose sur vous...",
    close: "Fermer",
    cancel: "Annuler",
    saveProfile: "Enregistrer le profil",
    saving: "Enregistrement...",
    usersLabel: "UTILISATEURS",
    activeReports: "SIGNALEMENTS ACTIFS",
    resolved: "R\u00C9SOLUS",
    donationsCollected: "DONS COLLECT\u00C9S",
    pointsDistributed: "POINTS DISTRIBU\u00C9S",
    partnersLabel: "PARTENAIRES",
    activeMissions: "MISSIONS ACTIVES",
    downloads: "T\u00C9L\u00C9CHARGEMENTS",
    thisWeek: "cette sem.",
    pending: "en attente",
    rate: "Taux",
    thisMonth206: "ce mois",
    pendingPoints: "en attente",
    inValidation: "en validation",
    inProgress: "en cours",
    thisMonth55: "ce mois",
    mapTitle: "Carte signalements",
    view: "Lire",
    activeReportsCount: "signalements actifs",
    recentActivity: "Activit\u00E9 r\u00E9cente",
    act1: "signalement chien perdu, Salon-de-Provence",
    act1time: "Il y a 2 min",
    act2: "vient de s'inscrire",
    act2time: "Il y a 8 min",
    act3: "Don de 20€ re\u00E7u \u2013 Mission SPA Salon",
    act3time: "Il y a 15 min",
    act4: "SPA Salon a valid\u00E9 4 participations mission Balade chiens",
    act4time: "Il y a 22 min",
    act5: "signalement r\u00E9solu \u2705",
    act5time: "Il y a 1h",
    whiteKitten: "Chaton blanc",
    reportTypes: "Types de signalements",
    lost: "Perdus",
    found: "Trouvés",
    sheltered: "Recueillis",
    injured: "Blessés",
    goal: "/ 5 000€ objectif",
    donors: "Donateurs",
    remaining: "Restants",
    left: "Restant",
    daysRemainingValue: "18j",
    // Signalements Page
    reportsTitle: "Signalements",
    reportsSub: "signalements actifs - r\u00E9solus",
    totalActive: "TOTAL ACTIFS",
    resolvedLabel: "R\u00C9SOLUS",
    pendingLabel: "EN ATTENTE",
    resolutionRate: "TAUX R\u00C9SOLUTION",
    allReports: "Tous les signalements",
    animal: "ANIMAL",
    type: "TYPE",
    status: "STATUT",
    location: "LOCALISATION",
    user: "UTILISATEUR",
    date: "DATE",
    actions: "ACTIONS",
    viewBtn: "Voir",
    editBtn: "Modifier",
    deleteBtn: "Supprimer",
    contactsTitle: "Contacts",
    contactsSub: "Contacts utiles pour la communaut\u00E9",
    addContact: "Ajouter un contact",
    contactName: "NOM",
    contactType: "TYPE",
    contactAddress: "ADRESSE",
    contactPhone: "T\u00C9L\u00C9PHONE",
    contactEmail: "E-MAIL",
    allContacts: "Tous les contacts",
    shelter: "Refuge",
    vet: "V\u00E9t\u00E9rinaire",
    association: "Association",
    partner: "Partenaire",
    editContact: "Modifier le contact",
    viewContact: "Voir le contact",
    validateBtn: "Valider",
    spamBtn: "Spam",
    // Users Page
    usersTitle: "Utilisateurs",
    usersSub: "1 284 inscrits",
    totalRegistered: "TOTAL INSCRITS",
    activeLabel: "ACTIFS",
    suspendedLabel: "SUSPENDUS",
    newThisMonth: "NOUVEAUX CE MOIS",
    allUsers: "Tous les utilisateurs",
    email: "EMAIL",
    points: "POINTS",
    missions: "MISSIONS",
    registration: "INSCRIPTION",
    detailsBtn: "Fiche",
    suspendBtn: "Suspendre",
    reactivateBtn: "R\u00E9activer",
    banBtn: "Bannir",
    exportBtn: "Exporter",
    // Partners Page
    partnersTitle: "Partenaires",
    partnersSub: "14 actifs - 3 en attente",
    pendingValidation: "En attente de validation",
    activePartners: "Partenaires actifs",
    pendingMissionValidations: "Validations missions en attente",
    participants: "PARTICIPANTS",
    validateAll: "Valider tout",
    addPartner: "Ajouter un partenaire",
    // Missions Page
    missionsTitle: "Missions locales",
    missionsSub: "8 missions - 2 en cours",
    inProgressLabel: "EN COURS",
    toComeLabel: "\u00C0 VENIR",
    finishedLabel: "TERMIN\u00C9ES",
    pointsAttributed: "PTS ATTRIBU\u00C9S",
    allMissions: "Toutes les missions",
    createMission: "Cr\u00E9er une mission",
    addMission: "Ajouter une mission",
    cancelBtn: "Annuler",
    // Points de collecte Page
    collectionPointsTitle: "Points de collecte",
    collectionPointsSub: "22 points actifs",
    pointsList: "Liste des points de collecte",
    addPoint: "Ajouter un point",
    deactivateBtn: "D\u00E9sactiver",
    // Points Page
    pointsTitle: "Syst\u00E8me de points",
    pointsSub: "18 450 pts distribu\u00C9S",
    distributedLabel: "DISTRIBU\u00C9S",
    exchangedLabel: "\u00C9CHANG\u00C9S",
    expiredLabel: "EXPIR\u00C9S",
    pointsScale: "Bar\u00E8me des points",
    usageRules: "R\u00E8gles d'utilisation",
    transactionHistory: "Historique des transactions",
    saveScale: "Enregistrer le bar\u00E8me",
    saveBtn: "Enregistrer",
    validityDuration: "Dur\u00E9e de validit\u00E9 - 12 mois",
    monthlyCeiling: "Plafond mensuel - 500 pts",
    doublePoints: "Double points actif",
    pointsOnDonations: "Points sur dons",
    // Physical Items Page
    itemsTitle: "Articles physiques",
    itemsSub: "Catalogue \u00E9changeable",
    addItem: "Ajouter un article",
    exchangeRequests: "Demandes d'\u00E9change",
    article: "ARTICLE",
    address: "ADRESSE",
    shippedBtn: "Exp\u00E9di\u00E9",
    restockBtn: "R\u00E9appro",
    outOfStock: "Rupture",
    // Donations Page
    donationsTitle: "Dons",
    donationsSub: "4 820€ collect\u00E9s",
    totalCollected: "TOTAL COLLECT\u00C9",
    returnedAssos: "REVERS\u00C9 ASSOS",
    averageBasket: "PANIER MOYEN",
    allTransactions: "Toutes les transactions",
    donator: "DONATEUR",
    amount: "MONTANT",
    association: "ASSOCIATION",
    fiscalReceipt: "Re\u00E7u fiscal",
    returnBtn: "Reverser",
    receiptBtn: "Re\u00E7u",
    // Crowdfunding Page
    crowdTitle: "Crowdfunding",
    crowdSub: "Campagne Ulule - 83% atteint",
    viewOnUlule: "Voir sur Ulule",
    donorsList: "Liste des donateurs",
    counterpart: "CONTREPARTIE",
    confirmed: "Confirm\u00E9",
    collected: "collect\u00E9s",
    futureLaunch: "Lancement futur",
    // Analytics Page
    analyticsTitle: "Analytics",
    analyticsSub: "Performances globales",
    sessionsMonth: "SESSIONS/MOIS",
    retention: "R\u00C9TENTION",
    avgDuration: "DUR\u00C9E MOY.",
    conversion: "CONVERSION",
    reportsMonth: "Signalements par mois",
    activeZones: "Zones les plus actives",
    zone1: "Provence-Alpes-C\u00F4te d'Azur",
    zone2: "\u00CEle-de-France",
    zone3: "Occitanie",
    zone4: "Auvergne-Rh\u00F4ne-Alpes",
    // Notifications Page
    notifTitle: "Notifications",
    notifSub: "Alertes communaut\u00E9",
    createAlert: "Cr\u00E9er une alerte",
    geoTarget: "CIBLAGE G\u00C9OGRAPHIQUE",
    userType: "TYPE D'UTILISATEURS",
    message: "MESSAGE",
    sendAlert: "Envoyer l'alerte",
    allFrance: "Toute la France",
    pacaRegion: "Provence-Alpes-Côte d'Azur",
    opening: "Ouverture",
    clicks: "Clics",
    enterAlertMessage: "Saisissez votre message d'alerte...",
    notifHistory: "Historique des notifications",
    // Settings Page
    settingsTitle: "Param\u00E8tres",
    settingsSub: "Configuration de la plateforme",
    adminTeam: "\u00C9quipe admin",
    application: "Application",
    recentLogins: "Derni\u00E8res connexions",
    inviteAdmin: "Inviter un admin",
    autoAlerts: "Alertes automatiques",
    pushNotifs: "Notifs push activ\u00E9es",
    maintenanceMode: "Mode maintenance",
    disableAccess: "D\u00E9sactive l'acc\u00E8s utilisateurs",
    alertRadius: "Rayon d'alerte",
    defaultGeo: "G\u00E9olocalisation par d\u00E9faut",
    saveChanges: "Enregistrer",
    supportSettings: "Param\u00E8tres de Support",
    supportEmailLabel: "E-mail de Support",
    supportEmailSub: "E-mail affich\u00E9 dans l'app mobile pour le contact utilisateur.",
    platformNameLabel: "Nom de la plateforme",
    platformNameSub: "Nom g\u00E9n\u00E9ral utilis\u00E9 dans l'application.",
    faqManagement: "Gestion de la FAQ",
    addFaq: "Ajouter une FAQ",
    allCategories: "Toutes les cat\u00E9gories",
    questionLabel: "Question",
    answerLabel: "R\u00E9ponse",
    noFaqsFound: "Aucune FAQ trouv\u00E9e.",
    faqTitle: "FAQ",
    faqSub: "G\u00E9rez le contenu du centre d'aide.",
    superAdminBadge: "SUPER ADMIN",
    // Validation Dons Page
    valDonationsTitle: "Preuves de Don",
    valDonationsSub: "4 dons en attente de validation",
    pendingValidationDon: "EN ATTENTE",
    validatedThisMonth: "VALID\u00C9S CE MOIS",
    refused: "REFUS\u00C9S",
    ptsGranted: "PTS ACCORD\u00C9S",
    howItWorks: "Comment \u00E7a fonctionne ?",
    howItWorksDesc: "L'utilisateur prend une photo de son d\u00E9p\u00F4t dans un point de collecte partenaire et la soumet via l'appli. Tu valides ou refuses ici. Les points (+15 pts) sont attribu\u00E9s automatiquement apr\u00E8s validation.",
    donsPendingVal: "Dons en attente de validation",
    recentValidations: "Validations r\u00E9centes",
    depositsThisMonth: "Stats d\u00E9p\u00F4ts ce mois",
    refusalReasons: "Motifs de refus fr\u00E9quents",
    validatePts: "Valider +15 pts",
    refuseBtn: "Refuser",
    enlargePhoto: "Agrandir la photo",
    // Report Form Additions
    createReport: "Créer un signalement",
    editReportTitle: "Modifier le signalement",
    createReportTitle: "Créer un nouveau signalement",
    newRecord: "Nouvel Enregistrement",
    fieldRequired: "Ce champ est requis",
    failedSaveReport: "Échec de l'enregistrement du signalement",
    animalName: "Nom de l'animal",
    breed: "Race",
    gender: "Sexe",
    male: "Mâle",
    female: "Femelle",
    age: "Âge",
    junior: "Junior",
    adult: "Adulte",
    senior: "Senior",
    eventDate: "Date de l'événement",
    locationAddress: "Adresse",
    hasMicrochip: "Pucé",
    hasTattoo: "Tatoué",
    hasCollarOrHarness: "Collier/Harnais",
    yes: "Oui",
    no: "Non",
    unknown: "Inconnu",
    animalPhoto: "Photo de l'animal",
    editFaqGroup: "Modifier le groupe FAQ",
    addFaqGroup: "Ajouter un groupe FAQ",
    viewFaqGroup: "Voir le groupe FAQ",
    viewFaq: "Voir la FAQ",
    groupOrder: "Ordre du groupe",
    qaOrder: "Ordre Q&R",
    questionsAndAnswers: "Questions & Réponses",
    addQa: " Ajouter Q&R",
    englishLang: "Anglais",
    frenchLang: "Français",
    englishQuestionPlaceholder: "Question en anglais...",
    englishAnswerPlaceholder: "Réponse en anglais...",
    frenchQuestionPlaceholder: "Question en français...",
    frenchAnswerPlaceholder: "Réponse en français...",
    atLeastOneQa: "Veuillez ajouter au moins une Q&R.",
    deleteFaqGroupMessage: "Voulez-vous vraiment supprimer ce groupe de FAQ ? Cette action est irréversible.",
    questionsCount: "QUESTIONS",
    questionsText: "Questions",
  },
};
const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem("adminLang") || "en");

  const handleSetLang = (newLang) => {
    setLang(newLang);
    localStorage.setItem("adminLang", newLang);
  };

  const t = translations[lang];

  return (
    <LanguageContext.Provider value={{ lang, setLang: handleSetLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLang() {
  return useContext(LanguageContext);
}
